### ISSUE TITLE
Compatibility issue with cVim on Vivaldi

### ISSUE THREAD

**Issue by danikron** [alexanderby/darkreader#107]
When opening the [cVim](https://github.com/1995eaton/chromium-vim) command frame (open, new tab, find, etc.) on Vivaldi (1.12 stable) on a site where darkreader is active the page behind it becomes blank (as long as the command frame is open). This does not happen with other inversion extensions found on the Chrome store or with userstyles.

**Comment by theolaurent** [comment]
I am facing the same issue. To me, it seems that darkreader does not take alpha channel into account when inversing background.

**Comment by alexanderby** [comment]
I've tried to install cVim, but I can't figure out how to use it. Can you give a hint?

**Comment by danikron** [comment]
Once cVim is installed just go to any webpage and hit "o" (without an input box focused). This should open an overlay that covers part of the page, with the rest of it turning white if darkreader is active and otherwise leaving it unchanged.

**Comment by alexanderby** [comment]
OK, I've added a fix, check it out within 15 minutes.

**Comment by danikron** [comment]
Seems to work here. That's quick work, and on a Saturday too. Great work and thank you very much!
