### ISSUE TITLE
What about Firefox version?

### ISSUE THREAD

**Issue by pshirshov** [alexanderby/darkreader#11]
Could you estimate efforts required for Firefox version? What about crowdfunding campaign?

**Comment by alexanderby** [comment]
Considering that some code and design can be shared, Dark Reader for Firefox can be done in 5 days and requires at least $750 to be complete as soon possible.
That would be nice as far as Firefox doesn't have all that [white flash issues](https://productforums.google.com/forum/#!topic/chrome/M_gtcHph_ZQ), and experience may be better than Chrome.
Your idea with crowdfunding is nice, but as far as I'm a citizen of Belarus, I'm not sure to be able to participate and have to make some research.

**Comment by FeiWongReed** [comment]
I may donate you $100, but $750 is too much for me )

**Comment by alexanderby** [comment]
Seems like you really need this extension :) I've tried to register a project at Kickstarter, but failed, maybe we need a US dude here. I'm too much busy to start working on it, but I will start reading Firefox docs, and maybe in a month or two I will port this extension, at least without the settings page.

**Comment by rileyjshaw** [comment]
You might want to look into [WebExtensions](https://blog.mozilla.org/addons/2015/08/21/the-future-of-developing-firefox-add-ons/) :)

**Comment by FeiWongReed** [comment]
WebExtensions are planned to be ready at end of 2016. And there is no guarantees that DR will work under WE.

**Comment by FeiWongReed** [comment]
I may register KS project for you, because I'm EU resident.

**Comment by DrupaListo-com** [comment]
or maybe indiegogo or bountysource?
@alexanderby check out bountysource - I think it uses paypal and maybe u got paypal?
You could split the 750 amount into say 10/15 sub-tasks and we go together and fund and release when you are done with each one?

My experience is with this project: https://github.com/borgbackup/borg and we use there bountysource successfully bug per bug + there is a whole-project bucket when somebody wants to just support ... I am mainly a user/tester and minor supporter with some bounties there.

Cheers.

**Comment by maun** [comment]
I am also very interested in this extension for Firefox (only because of these white flashes in chrome)

Instead of porting to the Firefox extension API which will be deprecated WebExtensions look like the better alternative. Has anyone tried packaging this extension for Firefox? [WebExtension Tutorial](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Your_first_WebExtension)

**Comment by maun** [comment]
@alexanderby I read that you are also annoyed by the white flash issue in Chrome. After trying a lot of browsers I found a setup without white flashes, just in case you or someone else is interested:

- Vivaldi Browser (Chromium engine + Chrome plugins supported):
https://vivaldi.net/teamblog/121-snapshot-1-3-501-6-customizable-ui-themes

The 1.3 prerelease has better theming support. (You can change the orange accent color to gray)

- Dark Reader extension of course

Create a local file `blackPage.html` with the following content:
```
<!doctype html>
<html style="background-color:#000000;">
  <head>
  </head>
  <body>
  </body>
</html>
```
Instead of black you can also set the color to the background color of your theme, this removes one more color change.

- Open the file in Vivalid and copy the path, use it to set this page as startpage and page for new tabs.

That's it :-) Just in case someone finds this with the same problem. I found some questions on Stackoverflow and the bugreports but no answer that works.

**Comment by alexanderby** [comment]
Thanks @maun for your interest in this problem. Seems like required APIs are supported in latest FireFox versions, so I'll try to port it.
Chrome white flash problem seems deeper, but we only have to report bugs.

**Comment by theghost5800** [comment]
Can I ask what happend with port to firefox?

**Comment by oxysoft** [comment]
I would like to know as well, Firefox has had several major optimizations in the past year or so and I decided to switch back to it today after getting pissed off with Chrome getting lags in weird ways, but I cannot live without Dark Reader. I can't imagine that it would be that hard to port it, most of the logic will probably be the same except for the extension API calls. Please add Firefox support asap

**Comment by Aqa-Ib** [comment]
Dark Reader on Firefox would be awesome. The only thing I like from Chrome is Dark Reader. Firefox is by far (at least in my computer) more responsive and quicker than Chrome, and doesn't have white flashes if you put a simple CSS style to avoid them. The only thing that I miss in Firefox is Dark Reader. I use a global dark css style in Firefox, but Dark Reader is by far the best, it is in another level.

Thank you very much for this great program and I hope that someday could be a reality in the best browser for my computer: Firefox.

**Comment by Aqa-Ib** [comment]
What about the crowdfounding campaign? I will donate with pleasure.

**Comment by alexanderby** [comment]
I agree, a year has passed, it's time to see the WebExtension progress. @pshirshov told that he could start the campaign at KickStarter. I will provide all necessary materials, text, posters etc.

**Comment by callahad** [comment]
We don't yet support the fontList API, but everything else seems to work without modification:

![screenshot](https://user-images.githubusercontent.com/24193/27212436-9eef039a-5225-11e7-8b1e-3bec52b6e9f5.png)

...I suspect this could literally be a one-line change + upload to https://addons.mozilla.org/ to get Dark Reader onto Firefox. Let me know if you need any assistance.

**Comment by alexanderby** [comment]
@callahad Could you please describe, what should be changed? I tried some auto conversion tools some month ago, but failed.

**Comment by nhumrich** [comment]
@callahad @alexanderby any update on this? Would love to see this on FF. This is really the only good dark reader I can find. All the existing FF versions aren't great.
WebExtension support on firefox should be complete now.

**Comment by freed00m** [comment]
@callahad could you please point us in the right direction of how did you build this for firefox? :)

**Comment by alexanderby** [comment]
I'll try to make FF version the next week.

**Comment by nemanjan00** [comment]
Also interested in this :)

**Comment by nemanjan00** [comment]
Here is version working in firefox: 

https://github.com/alexanderby/darkreader/pull/85


There are some visual bugs, and to solve them, for now, I use Stylus extension and this CSS: 

```CSS
body, html {
  background-color: #fff;
}
```

**Comment by nemanjan00** [comment]
Firefox version: 

https://addons.mozilla.org/en-US/firefox/addon/darkreader/

**Comment by alexanderby** [comment]
@nemanjan00 Publishing unstable and partially working extension hits Dark Reader reputation, so please, unpublish. If you wosh you can fork the extension and publish it without using Dark Reader name, mascot and logo.

I appreciate your interest in making a Firefox version, but it's not about making a fast code patch, so please wait until I finish code refactoring and configuring tests and build process.

**Comment by nemanjan00** [comment]
Can you at least merge my pull request so people can use it in firefox?

**Comment by nemanjan00** [comment]
[Version I built and signed](https://my.pcloud.com/publink/show?code=XZS7LoZ592QnBW1MW51WmbY7gk0pmfpmQLX)

**Comment by alexanderby** [comment]
I will review it first.

**Comment by alexanderby** [comment]
Now the extension works for Firefox. I've tried to publish it to Mozilla Addons. Unfortunately Mozilla team is very picky. They didn't like that I use `innerHTML` on popup page (there is no any possibility for XSS), have `fontSettings` API usage (though there is a check and fallback for missing API) and moderator saw an error in console (I guess some Firefox specific page is locked from extensions). So I asked for approve without any changes as far as there is no real reason for blocking it. If they still insist, it will require some more time to fix these issues.

**Comment by nemanjan00** [comment]
Until then you can host it somewhere outside their store. 

If you choose to host it on your own site, it does not require verification. 

You just need different id in manifest for it.

**Comment by alexanderby** [comment]
They still have to sign it. So until it is done you can try to [download](http://shutov.by/darkreader/darkreader-3.5.0-firefox.zip) the extension, unpack it, click Add-ons, then click Debug add-ons, Load temporary Add-on and point to extension's manifest.json file. There are some CSS issues, but everything else seems to work fine.

**Comment by nemanjan00** [comment]
They will sign it without verification if it is for your site and not addons store.

**Comment by nemanjan00** [comment]
This is the example I signed... 
https://transfer.sh/4h0Qe/dark_reader-3.5.0-an-fx.xpi

**Comment by inv2004** [comment]
Best extension for dark-mode. But ~ week ago I switched to firefox 58 beta, and prefer it like default browser. Ready to donate 20$.

**Comment by jankalfus** [comment]
@nemanjan00 Unfortunately, the one you posted for Firefox doesn't work as good as the original one. There are probably more changes required, that aren't apparent at first sight. Here's a quick comparison: 
![comparison](https://user-images.githubusercontent.com/12714276/32416920-89f7220a-c251-11e7-8f75-b68b81889be7.jpg)

**Comment by nemanjan00** [comment]
I just made it installable. 

There indeed are differences between browsers.

**Comment by deathtrip** [comment]
any status update on this?
has mozilla signed it or not?
now that firefox quantum has come out, it's the one extension i miss the most from chrome.

**Comment by alexanderby** [comment]
I'm rewriting the UI for better extensibility. This will also fix the `innerHTML` problem, that Mozilla team considers as a security issue. I hope to finish it by the end of year.

**Comment by JobLeonard** [comment]
In case this issue hasn't been reported yet: I loaded Dark Reader in Nightly, using through [Chrome Store Foxified](https://addons.mozilla.org/en-US/firefox/addon/chrome-store-foxified/) and it runs fine almost everywhere (except YouTube, which stutters, but YT has a built-in dark theme so doesn't need it).

However, there is one nagging bug: the position of direct image links is calculated wrong:

With Dark Reader on:

![image](https://user-images.githubusercontent.com/259840/33435065-786f5676-d5e1-11e7-8495-eaf49ccca766.png)

With Dark Reader toggled off:
![image](https://user-images.githubusercontent.com/259840/33435082-8546e922-d5e1-11e7-9a7c-112f6f187781.png)

(also, Dark Reader should probably not apply contrast/brightness/desaturation filter over the image whatsoever when loading not inverting an image - but I think #44 kind of covers that issue already)

**Comment by StefanoFrazzetto** [comment]
I have used Dark Reader on Chrome and I think it's one of the best plugins I have installed. I switched to Firefox now and I really miss it. Any update on when we will be able to see a Firefox version?

**Comment by alexanderby** [comment]
@StefanoFrazzetto I'm going to finish refactoring and publish it to Mozilla Addons during my Christmas holidays.

**Comment by pshirshov** [comment]
Don't forget about donation button

**Comment by veekas** [comment]
Hi @alexanderby. Adding my appreciation for Dark Reader in Chrome. I'm having trouble finding it in Mozilla Add-Ons. Were you able to publish it over the holidays?

**Comment by alexanderby** [comment]
The bad news is that I haven't made all the required changes during the holidays. The good news is that I've left my job and currently work on this project full time. While writing this, I didn't want to give you another time estimates, so I've added some quick fixes. Surprisingly the submission took some minutes, so you can [check it out](https://addons.mozilla.org/en-US/firefox/addon/darkreader/) now. Dark Reader will wink at first 15 users.

**Comment by JobLeonard** [comment]
Shit, I didn't look, now I'll never know!

**Comment by risualiser** [comment]
@alexanderby, what about taking part here? https://extensionschallenge.com/
(Of course, after the new release.)

**Comment by alexanderby** [comment]
@risualiser I've received an e-mail asking to take a part. But it seems like they will accept extensions that are using some new APIs for tab management and dynamic browser themes. I will apply as soon as the extension will work on Android.

**Comment by nhumrich** [comment]
> as soon as the extension will work on Android.
Is this real life, or is this make believe? 
That is all I have ever wanted in life.

**Comment by alexanderby** [comment]
It's working on Android starting from today. Static Theme mode is used by default because Filters (at least on my device) reduce battery life and are laggy. The next step is implementing Dynamic Theme mode, so that there will be no lags and the number of wrongly displayed elements will be reduced.

**Comment by tjkirch** [comment]
Thanks a lot for your work on this!  I'm loving it on Firefox desktop.  I'd like to donate towards your development, as long as there's a PayPal/Amazon/etc. link rather than a credit card box.

**Comment by Desimor** [comment]
I'd really like to know why Dark Reader Dynamic mode on Firefox is so laggy. It hangs the whole browser itself, scrolling is difficult, and pages load significantly slower. Dynamic Mode was the best thing that ever happened to Dark Reader. Even back when it was just static, I never switched to Firefox because of how good Dark Reader was. I'm so thankful for Dark Reader on Firefox now, but I'm really hoping it stops lagging in Dynamic Mode.

**Comment by alexanderby** [comment]
@Desimor It requires some time to make it more performant. When all the icons will be light and backgrounds will be dark we will focus on performance, caching the CSS analysis results, executing image analysis in web workers.

I've just published version 4.5.3 with some performance improvements, version 4.5.2 also had some.

**Comment by Aqa-Ib** [comment]
@Desimor it is not laggy for me. Can you try Dark Reader with a clean Firefox profile please?

**Comment by risualiser** [comment]
Same as @Aqa-Ib on desktop, but on mobile it takes 5-10 seconds to generate dark theme while it shows partically white theme.

**Comment by Desimor** [comment]
@Aqa-Ib I tried an upgrade to Firefox Nightly to see if that worked, but no luck. I'll try a fresh install.

**Comment by Aqa-Ib** [comment]
You only need to remove your user's firefox settings folder for a clean profile. In linux it's ~/.mozilla. In windows I guess that it is somewhere around here:  C:\Users\<username>\AppData\Roaming\Mozilla\Firefox\Profiles\xxxxxxxx.default

**Comment by Desimor** [comment]
I'm using linux mint at work right now. So you suggest removing the profile instead of the whole application itself?

**Comment by alexanderby** [comment]
Dynamic mode analyzes all CSS colors, CSS custom properties (variables), background images, inline styles for all elements with style attribute or SVG element. The performance varies on every web page. There is no need to remove user profile.

**Comment by Aqa-Ib** [comment]
Yeah, the reinstalling the whole application won't make sense. In your home folder there is a folder called .mozilla (notice the dot, it is a hidden folder). Backup it and remove it, then restart firefox.

**Comment by Aqa-Ib** [comment]
I mean, Desimor said that "It hangs the whole browser itself, scrolling is difficult, and pages load significantly slower". I never had a hand, never had a scrolling difficulty, and I had "pages that load significantly slower" only in this sense #512.

**Comment by Desimor** [comment]
Unfortunately, that didn't seem to make a difference. I'll try it at home on a Windows machine to see if there is a difference. If that doesn't work, I'll personally take a look at the time complexity of dark reader's algorithm for Dynamic Mode.

**Comment by Aqa-Ib** [comment]
Unfortunate @Desimor. Then maybe in the future you can see the improvements in performance that @alexanderby is working on.

Regards.

**Comment by alexanderby** [comment]
One of the reasons could be the difference in Chrome and Firefox when they show the page. Firefox doesn't show the page until the styles are loaded. At least it was so 3 years ago https://github.com/alexanderby/chrome-kills-eyes

So, maybe Firefox is waiting for network requests to complete (we are making extra requests due to CORS restrictions). Scrolling issues could happen when inline styles override was not optimized, but it is now much more better. Also my yesterdays performance fix for large image Data URLs didn't work on Firefox, seems like there was a bug that was fixed for Firefox 61 https://bugzilla.mozilla.org/show_bug.cgi?id=1450302
