### ISSUE TITLE
Google Play Books not showing the inverted colours

### ISSUE THREAD

**Issue by hangjitrai** [alexanderby/darkreader#110]
The background and the text colours in google books aren't getting inverted.
![image](https://user-images.githubusercontent.com/28245699/31701614-4ea78772-b41d-11e7-851e-6331812ddd62.png)

**Comment by RalphLesch** [comment]
Fast fix: add `.pageImageDisplay` under `invert` to the `google.*` inversion fix.
Loading pages are still displayed white, I do not know if that can be fixed, would require further investigation...

**Comment by alexanderby** [comment]
Should be fixed now.
