### ISSUE TITLE
Can't seem to get noinvert to work

### ISSUE THREAD

**Issue by Kevin-Mok** [alexanderby/darkreader#113]
So, I'm trying to get noinvert to work on an icon on rottentomatoes.com. I've got:
```
"url": "rottentomatoes.com",
"noinvert": ".icon, .tiny, .certified_fresh"
```
![Imgur](https://i.imgur.com/Dbn7O6hm.png)
I've read #91 and tried *'ing all the classes as well. What am I doing wrong?

**Comment by alexanderby** [comment]
Maybe you need to use "invert", here is the [explanation](https://github.com/alexanderby/darkreader/issues/91#issuecomment-330821253).

Inversion is applied to root "html" element, so you need to "invert" wrongly inverted elements again.
