### ISSUE TITLE
wildcard in site list doesn't always work

### ISSUE THREAD

**Issue by jmona789** [alexanderby/darkreader#119]
I use google photos for pictures, I like it inverted while browsing but not when viewing a picture because of he overlay adding "photos.google.com/photo" works but if I search for something and then view a picture the URL is "https://photos.google.com/search/query/photo/" so I tried adding 
"https://photos.google.com/search/*/photo or even "https://photos.google.com/*/photo/" to the not invert list but none of that works.  I tried serval different variations none of which work

**Comment by RalphLesch** [comment]
The star works only in the domain part, for the rest you can use some RegEx: `^photos.google.com/.*/photo/`.
See for e.g. [this comment](/alexanderby/darkreader/issues/86#issuecomment-355656408) for more details.

**Comment by alexanderby** [comment]
Unfortunately wildcards don't work well and need to be reworked.

**Comment by alexanderby** [comment]
It should work better with Dynamic Theme mode, but here is what is planned to do with list https://github.com/alexanderby/darkreader/issues/373
