### ISSUE TITLE
CHANGE HIGHLIGHT COLOUR -how?

### ISSUE THREAD

**Issue by WalterKemble** [alexanderby/darkreader#123]
Hello,
I am not a coder but am capable of following instructions to substitute code in a string. I LOVE the DARK EXTENSION FOR CHROME!! How can I change the highlight colour? As it is I have difficulty seeing what I'm highlighting. Thanks to anyone who can direct me in this.  BTW - am using 2016 27" iMac
xoxo   👁🤓👁

**Comment by alexanderby** [comment]
Are you trying to use Element picker in Chrome Developer Tools?

**Comment by alexanderby** [comment]
I didn't understand the problem, reopen and give more details if you still have the issue.
