### ISSUE TITLE
Do not invert google maps canvas

### ISSUE THREAD

**Issue by noonien** [alexanderby/darkreader#133]
The canvas at https://www.google.com/maps/ should not be inverted in street view mode.
This should apply to all google tlds.

**Comment by Mancerrss** [comment]
Yea it should only invert the search bar and the cards

**Comment by alexanderby** [comment]
You can add `google.*/maps` into an ignore list. I've just found a way to fix it (adding `"invert": ".app-globe-mode canvas"`), but there is an issue with animation during switching map modes.

**Comment by alexanderby** [comment]
Dynamic Theme mode doesn't touch the canvas, but I think it should be inverted when showing map only.
