### ISSUE TITLE
This is working on Firefox 57+

### ISSUE THREAD

**Issue by dumindu** [alexanderby/darkreader#134]
Hi,

Thanks for this amazing addon and please port this to Firefox. I tested this via https://addons.mozilla.org/en-US/firefox/addon/chrome-store-foxified/ and this is working perfectly on FF57+. So please officially port this to FF.

Thanks

**Comment by dumindu** [comment]
Also many FF users are waiting for your extension with https://www.reddit.com/r/firefox/comments/7focfv/for_night_owls_the_dark_mode/

**Comment by alexanderby** [comment]
Mozilla reviewers have found some problems, errors in console, so I'm rewriting the extension to fix them and hope to finish it by the end of year. Though really it requires some work days, maybe I'll find some time to finish it earlier. https://github.com/alexanderby/darkreader/issues/11
