### ISSUE TITLE
Dark reader doesn't work on the docs of gdax https://docs.gdax.com/

### ISSUE THREAD

**Issue by fad1** [alexanderby/darkreader#136]
https://docs.gdax.com/

Even the toggle button is disabled.

Curious as to what the cause is.

**Comment by charliepatt** [comment]
Seems to work just fine for me.

**Comment by alexanderby** [comment]
Maybe it used to be dark, one of contributors decided to add it into Dark List 2 years ago https://github.com/alexanderby/darkreader/blame/master/src/config/dark_sites.json#L22

**Comment by fad1** [comment]
Well, it doesn't work, the gdax docs page is very bright (white) and Dark reader Toggle button is not clickable.

**Comment by alexanderby** [comment]
Yeah, that's because it is added into global Dark List. If you are sure, that the website is always bright by default, I will exclude it from that list.

**Comment by alexanderby** [comment]
I've replaced `gdax.com` record with `www.gdax.com`, so the docs should be inverted now (after 15 minutes).

**Comment by fad1** [comment]
Works well now, thank you 👍
