### ISSUE TITLE
Content render lag on scroll

### ISSUE THREAD

**Issue by MythicalFish** [alexanderby/darkreader#144]
On most pages with darkreader enabled, if I scroll down too fast there's a delay of about a second before the content appears. Does anyone else have this issue?

**Comment by RalphLesch** [comment]
Dark Reader works by applying CSS filters (manly invert) on the entire page and several elements, like images (re-inverts), which is a rather expensive task and thus can slow down the page rendering.
There is nothing you can do about this without optimizing the CSS filter implementation itself, which would be a Browser issue, or by using a more efficient technique to darken / invert the pages, which does currently not exist to knowledge, at least not one which works on almost all pages with similar results.

**Comment by alexanderby** [comment]
I've experimented with CSS processor, that makes CSS like if it had a dark theme. There are some issues with not inverting icons and some bugs. Hope I will finish it this year. Currently you can use Stylish for heavy popular websites.

**Comment by alexanderby** [comment]
Dynamic Theme mode doesn't lag on scrolling, only may lag on initial page opening, when there are a lot of stylesheets and background images. It needs time to analise that all.
