### ISSUE TITLE
QR Codes should not be inverted

### ISSUE THREAD

**Issue by Muryoutaisuu** [alexanderby/darkreader#16]
Hi guys
I wanted to connect my iPhone to web.whatsapp.com, therefore I had to scan a QR Code with my iPhone. As dark reader also inverted the QR Code, my iPhone was not able to scan it. I needed some time until I understood that it was because of dark reader.

This issue is very low priority, but perhaps there is a way to detect whether an image is a QR Code?
In the case with whatsapp.com the image lies in a `<div>` called "qrcode".

It really is no big deal, as you can manually turn off dark reader for whatsapp.com. It just annoyed me for several days until I got the issue...

**Comment by Muryoutaisuu** [comment]
Oh my bad, I just saw, only the damn whatsapp logo is being inverted and preventing the scan from working.

It's described with
`<span class="icon icon-logo" data-reactid=".0.0:$qr-code.0.0.0.1"></span>`
no id, damn whatsapp...

**Comment by alexanderby** [comment]
Finally it didn't recognize the borders (at least on Win Phone), so I added a white border around this QR code.

**Comment by Muryoutaisuu** [comment]
awesome, thank you!

**Comment by xmha97** [comment]
same problem
