### ISSUE TITLE
Why do changes made in the "Developer Tools" reset themselves. Have to click "Apply" to reapply them.

### ISSUE THREAD

**Issue by Mav3r1x** [alexanderby/darkreader#162]
Hi there. I have small nifty codes for several sites to make them look good. Most of the sites are private like University's students portal, so obviously I can't create a pull request for them. But seems like changes made through the developer tools aren't applied on browser restart and you have to click apply to reapply those changes.

I don't want to create pull request for every little code I've added in the developer tools. I'm not sure but I think this is intentionally by the developer so that the user has to create a pull request for the changes to be permanent and to be applied automatically.

Please let me know if I'm wrong and this is just some issue with only my chrome.

Thanks.

**Comment by alexanderby** [comment]
You are right, the developer tools will be improved https://github.com/alexanderby/darkreader/issues/143
