### ISSUE TITLE
Is there any way to change the background color?

### ISSUE THREAD

**Issue by wyfang** [alexanderby/darkreader#169]
Because I do not understand the code, so to ask everyone. This tool looks like a direct reversal of the color of the page, some pictures will not be reversed, the idea is great. However, I found that since most web pages are white, the background is black when turned on. But pure black is obviously not good for vision and reading, so I wondered if there's any way to make the whole page grayer, such as # 1B1B1B (Adobe's black background).

Of course, I found that changing the two values can achieve the background color gray, but this will lead to the picture also followed by gray, because I am a visual designer, so to see the picture is very important to me.
![artboard](https://user-images.githubusercontent.com/17900420/34477698-007e0d1e-efd7-11e7-8272-cb99898f05b3.png)

**Comment by DanRathbun** [comment]
Read the README, and you'll need to learn CSS and understand HTML documents.

https://github.com/alexanderby/darkreader/blob/master/README.md

**Comment by alexanderby** [comment]
I will add some experimental filters soon.

**Comment by felidadae** [comment]
https://github.com/alexanderby/darkreader/issues/99 duplicate

**Comment by alexanderby** [comment]
So, I've added SVG filter, Static Theme and Dynamic Theme modes to try. Dynamic Theme is the best one and will become default after some improvements.
