### ISSUE TITLE
Text rendering issues

### ISSUE THREAD

**Issue by Hexodus** [alexanderby/darkreader#18]
The text isn't rendered properly IMHO - somehow it's not looking clean and is difficult to read. I even see it on your screenshots. There is a noticeable difference between the font on pages that are designed to be dark and the view created by this extension. It feels like the "text stroke" option is never really disabled even when it tells that it's switched off.

Anyways - this is a very cool and useful extension I've been waiting for. A big thank your for sharing it!

UPDATE:
I just found an easy work around:

	html {
	    text-shadow: 0 0 0 rgba(0,0,0,0.5);
	}

This is also being inverted so the result is higher text contrast - the bitten out parts are being smoothed ;)

**Comment by alexanderby** [comment]
Nice solution, thanks, will be released soon.

**Comment by Hexodus** [comment]
Many thanks ;)
