### ISSUE TITLE
What's the behavior of having empty string in `noinvert` rule?

### ISSUE THREAD

**Issue by kai-ming-91** [alexanderby/darkreader#183]
Hi, 

In Trello, all the menu, card, list, pop-over is properly inverted to dark background. However, if I apply a background to it, all of them will become white again.

I'm trying to fix it and I manage to come out (accidentally) with the following:

```json
        {
            "url": "trello.com",
            "invert": [
                ".body-custom-board-background .list",
                ".body-custom-board-background .board-menu-tab-content",
                ".body-custom-board-background .pop-over",
                ".body-custom-board-background .boards-drawer",
                ".body-custom-board-background .window-overlay"
            ],
            "noinvert": [
                ""
            ]
        }
```

I couldn't have all the card, list, menu, pop-over in dark colour without adding empty string to `noinvert` rule.

So what is the behaviour of `noinvert` rule? Is the configuration correct?

**Comment by alexanderby** [comment]
It just breaks injected CSS. Dark Reader sets dark background to root `<html>` element (since Chromium team decided to follow HTML5 spec and not invert root background). Maybe this color gets inverted in elements you listed. Try setting `"rules": "body { white !important; }"`.

**Comment by kai-ming-91** [comment]
I've try setting the `rules`, seems like working good :D Thanks!

I will test it a bit more before creating pull request.
