### ISSUE TITLE
Some sites fail to render in latest Chrome Canary (66)

### ISSUE THREAD

**Issue by abstiles** [alexanderby/darkreader#189]
Example of a failing site: [github.com](https://github.com).

Tested with a MacOs 10.11 machine on Chrome 66. The site renders entirely black when dark mode is enabled.

I believe this is related to an issue I filed against Chromium, [bug 804164](https://bugs.chromium.org/p/chromium/issues/detail?id=804164), due to similar problems on my own extension. My users also report issues on the Dev channel with Chrome 65 on Windows 10. At this time, Beta is Chrome 64 and Stable is Chrome 63.

Since this also affects you, I thought I'd give you what information I have. You might want to do your own investigation and add detail to the bug I filed. I have not yet found any good workarounds.

**Comment by abstiles** [comment]
What I've found in my own testing:

* Avoid using a contrast filter together with a hue-rotate filter.
* Avoid using a brightness filter greater than 100% combined with a contrast filter.

For the first point, you can work around this by using an invert filter less than 100%. For example, I believe the equivalent of `invert(100%) hue-rotate(180deg) contrast(90%)` is `invert(95%) hue-rotate(180deg)`.

**Comment by alexanderby** [comment]
Thank you for filing a Chromium issue. I've noticed that sometimes webpages become blank when filter is applied to dynamic content or for some other reasons, but haven't investigated yet. I don't see the issue you described on my current machine (Windows 10, Intel(R) HD Graphics 530), will try on another one.

**Comment by alexanderby** [comment]
So, the problem is that Chrome 65 works bad with Mac OS below 10.13.
