### ISSUE TITLE
Subdomains inherit toggle status from parent

### ISSUE THREAD

**Issue by jhoff** [alexanderby/darkreader#19]
So I realize that this behavior is by design, but it took me a while to figure out what was happening, so I thought I'd drop an issue here to see what other people thought.

I often run into an issue where I am working on a development version of my own site and all of a sudden I'm not able to toggle it on and off. I finally realized what the issue was.

Lets say I'm developing a site where production is example.com and development is at dev.example.com. I'm not only constantly switching between the two during development, but I'm toggling dark reader off and on for both in order to check CSS and other design aspects.

If I toggle dark reader off in production ( example.com ), then development ( dev.example.com ) will follow that setting and will no longer be togglable. This is because example.com is added to the "not inverted site list" and applies to all subdomains automatically. When I toggle dev.example.com, it is added and removed from the "not inverted site list", but because example.com overrides it, the toggle has no effect.

Perhaps adding a list of sites that have to match the full domain exactly in order for the toggle to apply?

**Comment by prasoc** [comment]
Yes, this issue is EXTREMELY irritating! I will fork the extension and fix this bug

**Comment by alexanderby** [comment]
I've added a support for `^` symbol, so `^github.com` will match `github.com/...` but will not match `gist.github.com`.

Also you can use `$` and `*` symbols, e.g. `github.*/alexanderby$` will match `github.com/alexanderby` but will not match `github.com/alexanderby/darkreader`.

Changes will be published soon.

**Comment by zkendall** [comment]
This ability needs documented somewhere, since the key toggling still doesn't work for me.

**Comment by alexanderby** [comment]
@zkendall See how you should setup a hotkey:
1. Click on the hotkey link.
![dr-hotkey](https://cloud.githubusercontent.com/assets/9638588/15738028/f523dbd0-28b1-11e6-8300-cd79b863ced1.png)
2. Setup your hotkey.
![dr-hotkey-set](https://cloud.githubusercontent.com/assets/9638588/15738242/1e467d0a-28b3-11e6-832f-a4c96d56c798.png)

But this will invert all sub-domain. If you want to protect from inversion root domain only, go to Site List tab and add `^` at the beginning of the host name.
![dr-root-match](https://cloud.githubusercontent.com/assets/9638588/15738168/b3338c38-28b2-11e6-91c3-ace4fa066718.png)

**Comment by zkendall** [comment]
I have my hotkey setup. Here's what I experience: If I have github.com NOT inverted, then my hotkey works on gist.github.com. However, if I have github.com inverted, then when I go to gist.github.com the hotkey no longer toggles the site.

**Comment by alexanderby** [comment]
@zkendall The hotkey (the same as Toggle button) simply adds or removes current resource name part of the URL to or from the Site List. So, open the Site List tab, see if you selected "Invert listed only" or "Not invert listed", and check the resource names in the list. 100% toggling the site may be complex, as far as current site toggling may be blocked by other rules, global Dark Sites list and Google Chrome itself (Chrome Web Store, chrome:// pages etc.).

**Comment by zkendall** [comment]
I understand, and got it to work, just thought it was peculiar. Advanced users can handle this. Common users will not bother or be confused.
