### ISSUE TITLE
Color edition

### ISSUE THREAD

**Issue by txomon** [alexanderby/darkreader#21]
I have been using the extension for a while and I realized that it's really troublesome to pick up a color because all of the colors are inverted, and the text I am writing it inherits them.

I have no idea on how I would solve this, but at least I will fill this issue.

A simple color edition place is atlassian.

Demo place https://demo.stiltsoft.com/pages/createpage.action?spaceKey=CIPE

**Comment by alexanderby** [comment]
For all the blocks which should not be inverted, but were inverted automatically, special rule have to be created [here](https://github.com/alexanderby/darkreader/blob/master/src/config/sites_fixes.json).

**Comment by alexanderby** [comment]
Could you please check if there is an issue with Dynamic Theme mode?

**Comment by txomon** [comment]
Sorry, I don't understand what you mean specifically

**Comment by txomon** [comment]
So I have checked now in two browsers, and with my config:
 * Brightness -20
 * Contrast -20
 * Grayscale +3
 * Sepia off

In Firefox it works OK, and in Chrome it doesn't.

About the themes, it works good on Dynamic and Static, and the problem arises on Filter and Filter+ modes.

**Comment by alexanderby** [comment]
Dynamic Theme will be default after some improvements, it's pretty hard to fix issues like this with CSS filters and such fixes work slow and buggy on devices with slow GPU and outdated video drivers.

By the way guys from StiltSoft are my fellow-students, I've made this S-legged logo long time ago :)
