### ISSUE TITLE
Darken entire browser ?

### ISSUE THREAD

**Issue by Rockvole** [alexanderby/darkreader#214]
Hi Alexander,
Excellent work with this plugin - best one I tried for browser darkening.

Is there a way to darken the rest of the browser - e.g. tabs, url bar, bookmarks & scrollbar ?
It would be a good addition to this extension if possible.

Thank-you.

**Comment by RalphLesch** [comment]
You need a dark browser theme for that, not an extension.

For **Chrome/Chromium** see [help page about chrome themes](https://support.google.com/chrome_webstore/answer/148695?hl=en).
An example for a dark theme would be [Morpheon Dark](https://chrome.google.com/webstore/detail/morpheon-dark/mafbdhjdkjnoafhfelkjpchpaepjknad).
Afaik not everything of the browser UI can be changed in Chrome. Other Chromium based browsers like [Vivaldi](https://vivaldi.com) support more customization.

I think **Firefox** has now a native Dark theme (under Addon settings).

**Comment by Rockvole** [comment]
I realised that in Linux mint the chromium browser followed my desktop dark theme, but google chrome didnt. I installed Morpheon Dark and it works well.
Thanks Ralph.
