### ISSUE TITLE
Extension UI blank in Firefox Private Browsing mode

### ISSUE THREAD

**Issue by joshsleeper** [alexanderby/darkreader#217]
# problem
Dark Reader UI is not displaying properly when in Private Browsing mode.

### example missing dark reader ui
![image](https://user-images.githubusercontent.com/849941/35940277-76841cfe-0c03-11e8-9613-9c08245a627b.png)

# specs
* Window 10 Pro 64-bit
* Firefox 58.0.2
* Dark Reader 3.5.3

**Comment by Oros42** [comment]
Same problem for me.
Firefox 58.0.2 (64bits) under GNU/Linux and Dark Reader 3.5.3.

**Comment by alexanderby** [comment]
That's ugly, but Firefox doesn't support some API in private mode https://bugzilla.mozilla.org/show_bug.cgi?id=1329304

I've already started a refactoring to make it work.
