### ISSUE TITLE
Dark Reader breaks some floating content when active

### ISSUE THREAD

**Issue by joshsleeper** [alexanderby/darkreader#218]
# problem
Footer on Gizmodo Media Group sites (gizmodo, kotaku, jalopnik etc.) is fixed at the bottom of the **initial** viewport and doesn't account for scrolling when Dark Reader is enabled. This usually results in covered article text. With Dark Reader disabled, the footer sticks to the bottom of the **current** viewport as intended, including when scrolling.
The image viewer also appears to be affected similarly, always displaying at the very top of the page instead of the current viewport.

### DR enabled, initial viewport
![image](https://user-images.githubusercontent.com/849941/35941317-af7fb06a-0c06-11e8-80cb-ecdb2394666f.png)

### DR enabled, scrolled down a bit
![image](https://user-images.githubusercontent.com/849941/35941339-bd2b714a-0c06-11e8-937a-3f66d1a5a13b.png)

### DR disabled, initial viewport
![image](https://user-images.githubusercontent.com/849941/35941354-c87b3d3c-0c06-11e8-8736-ef260284d6f3.png)

### DR disabled, scrolled down a bit
![image](https://user-images.githubusercontent.com/849941/35941360-cf8cd5ae-0c06-11e8-8fde-f525a3b2ac55.png)

### DR enabled, initial viewport
![image](https://user-images.githubusercontent.com/849941/35942467-9502c0ca-0c0a-11e8-8480-b231305fa4e3.png)

### DR enabled, scrolled down a bit
![image](https://user-images.githubusercontent.com/849941/35942476-9b347d76-0c0a-11e8-8684-8f1afb7b8a27.png)

# aside
I'm pretty sure I've seen this same breaking behavior on some other sites, but can't find any others to list at this moment.

# specs
* Window 10 Pro 64-bit
* Firefox 58.0.2
* Dark Reader 3.5.3

**Comment by RalphLesch** [comment]
That has to do with the policy from CSS filter for absolute positioned elements, which I cannot find a reference for atm. A solution in most cases is to set another parent element relative positioned.

**Comment by mfhscoobydoo** [comment]
looks like this only happens with the filter and filter+ engines, its a shame, I liked the filter engine.

**Comment by mfhscoobydoo** [comment]
some other sites you might be able to test with are soundcloud, and inbox.google.com

**Comment by alexanderby** [comment]
This is a browser bug. The only thing we can do is to file Chromium or Firefox issues. But I cannot remember any fixed filter issue, many of them are open for years. That's one of the reasons why I implemented a Dynamic Theme mode. Currently I don't see any problem that cannot be fixed, if you see the issues, please submit.
