### ISSUE TITLE
Use YAML or CSON for configs?

### ISSUE THREAD

**Issue by BANOnotIT** [alexanderby/darkreader#229]
JSON is good format, but it isn't for humans, it has many syntax salt. 

Why not to use [YAML](http://yaml.org/) or [CSON](https://github.com/bevry/cson) instead? So they can be easily edited and spacing there is salt. It can be converted into JSON easily by Grunt and Travis and delivered to users like it is now.

**Comment by alexanderby** [comment]
You are right, YAML is better for manual editing than JSON. But there are some reasons for using it:
1. JSON parser and formatter are built-in, and the whole system remains simple.
2. Both JSON and YAML syntax is hard to understand for non-technical users (e.g. people don't count spaces and the whole file breaks). Better solution would be custom text format similar to this example
```
@ google.*
INVERT
.fix-1, .fix-2,
.fix-3
NO INVERT
.fix-4
RULES
.fade {
    background: rgba(0, 0, 0, 0.5);
}

@ skype.com
INVERT
.icon
```
3. Historically we have JSON :) Installed copies of extension reads this config every 15 minutes. Changing config format and supporting both versions is painful.
4. There was an idea to use UI editor like http://jeremydorn.com/json-editor/
5. The idea with config containing manual fixes is moving into wrong direction. The config file grows, these 27KB are downloaded by 300,000 users every 15 minutes, and these numbers will grow, GitHub can stop or throttle file access for that. At the same time many websites are hard to fix with config (e.g. when there is dark header and light content). CSS filters have bugs in Chrome and more bugs in FireFox and performance is slow on many machines and mobile devices.

In the nearest future (hope the next week) I will finish the UI refactoring. Config editor will be moved into separate page.

After that I will continue working on CSS crawler, that analyzes web page stylesheets, images, elements and generates a dark theme. This will eliminate CSS filters and config with inversion fixes, improve performance and look. Of course this will introduce new kind of problems, but this approach looks more viable.

**Comment by alexanderby** [comment]
I think I will implement a custom file format. There are a lot of issues regarding sub-domain control, regexps, multilines and custom file format sounds like a solution.

**Comment by BANOnotIT** [comment]
2. CSS is hard to understand too, but fixes are writing with that "hard to understand to non technical people" language.
3. Own text format without indenting will rise problems with readability.

I think that UI for adding fixes will solve problem with text format, so you could use any format to reduce config size.
Have you seen UI for adding banners to blocklist in ad{block, hide, etc.}? I think you can do the same think, and this will solve problem with non technical users)

5. I agree that manual configs is bad in general, but we can't live without them, any algorithm will have bugs, that can be fixed manually.

PS
Didn't you thought about server, that renders site in PhantomJS or etc. and analyze its screenshot with python or anything else?

**Comment by alexanderby** [comment]
Having Element Picker would be great.

I've experimented with parsing CSS, it would be rather performant to generate CSS on the fly. But what about screenshot analysis, it seems an interesting problem, but I think it will freeze the user's CPU for some time. Creating a server for that will also increase a time of waiting for results and make the whole app complex and hard to maintain.
