### ISSUE TITLE
Bold text is harder to recognize

### ISSUE THREAD

**Issue by xged** [alexanderby/darkreader#23]
E.g. bold keywords in *Google-Search snippets*. Any workarounds?

**Comment by alexanderby** [comment]
I've added some text stroke for <em>, <strong> and <b> tags, looks a little bit blurry, but text is more recognizable.

**Comment by xged** [comment]
How about making regular font thinner (with *text-stroke* off)?

**Comment by isaacdnew** [comment]
Can this issue be re-opened? I still find bold text easy to miss, and it would be nice to have the option to brighten bold text.
