### ISSUE TITLE
Suggestion to add more screen shots to addons.mozilla.org  

### ISSUE THREAD

**Issue by dumindu** [alexanderby/darkreader#244]
Feel free to use any images of https://imgur.com/a/7eiR6 , https://imgur.com/a/D4LCn#XBgJHK2

And I share this on [/r/firefox](https://www.reddit.com/r/firefox/comments/7yvrkw/popular_chrome_extension_dark_reader_now_supports/) 

Thanks for porting this to FF :)

**Comment by alexanderby** [comment]
Thanks, will add some.

**Comment by alexanderby** [comment]
I've added some screenshots with dynamic theme mode, it looks better and tab colors are also inverted in Firefox 60.
