### ISSUE TITLE
Support Firefox Mobile

### ISSUE THREAD

**Issue by killoid** [alexanderby/darkreader#245]
it would be very useful for firefox mobile users. i have installed it already but it seems that it doesn't work.

**Comment by alexanderby** [comment]
I've just removed it from Android compatibility list. Will try to debug it the next week.

**Comment by orionlee** [comment]
In case it helps, I did a quick inspection for Firefox Android case. 
1. The DarkReader object is created in both the (empty-ish) pop-up and background page. However, at the minimal, the one in pop-up does not seem to be constructed completely (by a comparison with the ones on Firefox Desktop). 
2. There is no error message in developer console either.

**Comment by robsmith11** [comment]
FYI, it's still listed as available for android on the mozilla add-on page.

**Comment by alexanderby** [comment]
Just published v4.0.0, it should work on Android. Static Theme is used by default, as far as Filters are slow on smartphones.
