### ISSUE TITLE
choppy scrolling with certain extensions

### ISSUE THREAD

**Issue by deathtrip** [alexanderby/darkreader#256]
Since approximately the last version, when using Dark Reader with Scrollbar Anywhere extension on chrome, or with ScrollAnywhere on firefox, scrolling becomes choppy. Especially on sites with a lot of content. It only slows down when you drag the page, not the scrollbar. The problem goes away when Dark Reader is disabled. It worked fine on chrome before the current version.

**Comment by alexanderby** [comment]
Maybe you had Mac OS below 10.13, it works bad with Chrome 65. Dynamic Theme should be much more performant.
