### ISSUE TITLE
Pages load slow with glitchy full page text only before stablizing when loaded page is complete

### ISSUE THREAD

**Issue by blade1417** [alexanderby/darkreader#257]
I disabled all add-ons and that doesn't work. had no issue before Firefox 57 update, and uninstalled then reinstalled. Simple CSS works but real slow after the pages loads. Spreadsheet processor works best after pages loads but real glitchy and slow loading times. I prefer Spreadsheet processor but after Firefox 57 update it started doing this. Firefox 56 it worked fine.

i use windows 10 btw

**Comment by demir-delic** [comment]
I have the same issue on version 3.5.3 of Dark Reader. I'm on Firefox 58.0.2, MacOS. This is the first version of the extension that I've installed, so I don't know whether a recent breaking change is at fault.

Issues:
1. Pages load significantly more slowly, with assets slowly popping in one by one
2. Scrolling is very choppy
3. Videos on YouTube (haven't tested other sites) are choppy

**Comment by blade1417** [comment]
hopefully the add on creator fixes the bug soon.

**Comment by demir-delic** [comment]
I read some of the reviews on the [Chrome version of the extension](https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh/reviews?hl=en), and someone reported this issue as far back as October 2016, so it's nothing new. I wouldn't count on a quick fix.

**Comment by blade1417** [comment]
damn i hope he does lol

**Comment by alexanderby** [comment]
There is no way to speed up the CSS filters, it's optimization and fixing glitches is not in priority for browser developers. The only way to speed them up is to use more perfomant CPU and GPU. This will be fixed by using non-filter approach, some experimental options will be added soon. Until it's done you can use Stylish extension for popular heavy web pages. By the way YouTube has a built-in dark theme now.

**Comment by alexanderby** [comment]
Dynamic Theme mode should not be glitchy, except initial page load. I cannot do anything to speed up CSS filters or prevent browser rendering bugs, so file new issues if you see something wrong with Dynamic Theme mode.
