### ISSUE TITLE
Loading a direct url to an image makes it render with an offset

### ISSUE THREAD

**Issue by sandorex** [alexanderby/darkreader#260]
![Example](https://user-images.githubusercontent.com/18004075/36770982-dfe82cf8-1c4d-11e8-8992-0264916c8bf1.png)

The [Image](https://memegenerator.net/img/images/7680973.jpg)

After turning Dark Reader off its normal
Im using Firefox Beta (59.0b12) on Windows 10 1709

**Comment by geeknik** [comment]
And with Firefox Nightly (60.0a1) on Fedora as well.

**Comment by sandorex** [comment]
It also interferes with Imagus extension

**Comment by MindlessCirno** [comment]
I think it's firefox bug, so we should post it on bugzilla. Offset is added when we apply -webkit-filter: invert(100%) !important; to body or html element of page

**Comment by sandorex** [comment]
they are gonna probably say its the addon

**Comment by sandorex** [comment]
@MindlessCirno seems like you are right https://github.com/alexanderby/darkreader/issues/260

**Comment by MindlessCirno** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1449142#c5 
I reported this bug. Most likely it will not be fixed soon

**Comment by alexanderby** [comment]
Dynamic Theme mode doesn't use CSS Filters, so this bug is not reproduced.
