### ISSUE TITLE
Blank screen on some websites

### ISSUE THREAD

**Issue by poma** [alexanderby/darkreader#271]
Starting from yesterday some sites display black page when Dark Reader is enabled.  There was no such issue previously. I've tried to reset settings and reinstall but it doesn't help.

Examples of sites with this problem: stackoverflow.com, slack.com, vk.com

Update: If I set all controls to off (brightness, contrast, grayscale, sepia) it works correctly. Changing even one of those settings causes black screen.

Chrome version: 65.0.3325.146 (Official Build) (64-bit)

**Comment by poma** [comment]
Update: If I set all controls to off (brightness, contrast, grayscale, sepia) it works correctly. Changing even one of those settings causes black screen.

Chrome version: 65.0.3325.146 (Official Build) (64-bit)

**Comment by alexanderby** [comment]
Hi. This happens for some users. Please, share your OS, CPU and GPU. Have a look at this issue https://bugs.chromium.org/p/chromium/issues/detail?id=804164 if possible give the details there too.

**Comment by poma** [comment]
Added details to this issue. Interestingly, if I switch to discrete GPU this issue disappears.

**Comment by alexanderby** [comment]
Thanks.

**Comment by insprintorob** [comment]
got it in Version 65.0.3325.162 (Official Build) (64-bit)
Mac OS X

Looks like that chromium bug made it into the stable release.

**Comment by RobertLowe** [comment]
BUMP.

For anyone looking to a possible work around: I found restarting Chrome resolved the issue curiously enough, it appears to be an issue with the Intel GPU. As so linked above.

**Comment by alexanderby** [comment]
Fixed by implementing Dynamic Theme mode, which doesn't use CSS filters.
