### ISSUE TITLE
White text that has been changed to black looks slightly bolded or pixelated

### ISSUE THREAD

**Issue by YangVincent** [alexanderby/darkreader#276]
This happens on messenger.com as well as a variety of other websites.

**Comment by arthurblake** [comment]
Just started using this plugin and it's awesome I agree this is probably the biggest annoyance I've noticed so far.  It's on this very page! (see the Open button below)
![screen shot 2018-04-12 at 3 47 05 pm](https://user-images.githubusercontent.com/247797/38700358-c9ae3f80-3e68-11e8-85d1-3b51a24c91aa.png)
I don't understand why it's happening, but I would like to see a fix as well...

**Comment by alexanderby** [comment]
The problem is that CSS filters disable sub-pixel rendering. There is no such problem with Dynamic Theme mode, which replaces CSS colors without using CSS filters.
