### ISSUE TITLE
Top level images in Firefox 57 are truncated 

### ISSUE THREAD

**Issue by Curtisdhi** [alexanderby/darkreader#278]
When viewing images without any content, they are truncated about 50% from the top.
 Here is an example https://imgur.com/uuaAwVS and the original image https://upload.wikimedia.org/wikipedia/commons/c/c1/Test_wiki_logo_notext.png

Disabling the css rule on the HTML element "-webkit-filter: invert(100%) hue-rotate(180deg) brightness(110%) contrast(90%) grayscale(20%) sepia(10%) !important;" seems to fix the problem. But not sure if that is the root cause.

**Comment by sandorex** [comment]
Same as https://github.com/alexanderby/darkreader/issues/260

**Comment by alexanderby** [comment]
Fixed in Dynamic Theme mode.
