### ISSUE TITLE
Youtube videos slightly desaturated [Notable when full screening]

### ISSUE THREAD

**Issue by Rrojas117** [alexanderby/darkreader#29]
When your watching videos in Youtube you can tell some colors are off just by switching to full screen and back. Any way to fix this? Not a major issue but sure is an improvement.

**Comment by alejandro5042** [comment]
This is any video, not just YouTube. Videos should not be shaded. Also Google images and Flickr... these image services should not be shaded either. Where the media *is* the focus, it should not be shaded.

**Comment by alexanderby** [comment]
20% shade was removed from reverted blocks.
