### ISSUE TITLE
Feature request: gamma correction for LCD monitors

### ISSUE THREAD

**Issue by ershov** [alexanderby/darkreader#30]
Hi,
I'm not quite sure this is possible to do but I have to ask.

My problem is: on some sites I can't see light yellow highlighted text while inverted.
Turns out that LCD monitors are known to use gamma correction (some info can be found here http://www.eizoglobal.com/library/basics/lcd_display_gamma/ )
What it means to me: as you can see, less difference in light range (on the right) lead to more difference than the same numeric difference in dark range (on the left).

Hence, the proper way to invert an image would be:
1. Un-gamma = apply (1/gamma)
2. Invert
3. Apply gamma

This could be an additional filter and gamma value slider.

I work a lot with code, this would be extremely useful.

**Comment by alexanderby** [comment]
Try playing with brightness and contrast (pulling into opposite directions). I think this is similar to gamma correction.

**Comment by ershov** [comment]
Well I see.
There's no 'gamma' filter exist in web browsers.
