### ISSUE TITLE
imdb.com overlays

### ISSUE THREAD

**Issue by bigpalu** [alexanderby/darkreader#301]
I'm continuing with issues related to IMDB. The dropdown search results are hiding behind news section. 
![dark reader overlays](https://user-images.githubusercontent.com/37696185/37826693-cb260ce6-2e94-11e8-9439-adb0eba91723.PNG)
PS: I'm using Iron, if that helps.

**Comment by risualiser** [comment]
Fixed. Reopen your browser and try to visit it now.

**Comment by bigpalu** [comment]
perfect!
