### ISSUE TITLE
Infinite scroll issue

### ISSUE THREAD

**Issue by acohen27** [alexanderby/darkreader#31]
I got a question about Dark Reader. 

I have a MacBook Pro with OS X El Capitan‎. I noticed that when I go into gmail.com, I cannot scroll down with my mouse or trackpad while having darkreader enabled. The only way I can scroll down is by dragging the scrollbar with the mouse. 

Would you know what may cause that issue?

Thank you so much!

**Comment by alexanderby** [comment]
@acohen27 While using Dark Reader, open Developer Tools and add inline CSS rule `min-height: initial !important` to root `<html>` element and see if it fixes the problem. Unfortunately I have no Mac Book, so I cannot try it myself in the meantime.

**Comment by acohen27** [comment]
Hi there, 

I just tried adding the style rule in html’s head.  I also tried adding the attribute to the body and some of the divs. No luck. 

I also just tried dark reader on Chrome on my PC and it seems to work.  That is really strange. 

Wonder if it has to do anything with 
http://stackoverflow.com/questions/30280061/simple-css-codes-works-on-windows-but-not-on-mac-no-answers-found-on-the-inter

"I found the answer! The problem is that the encoding of the html file is different from the encoding of the CSS file. Originally, the html file use UTF-16LE and CSS file use windows-1252. Then, I tired to copy the same codes to a new html file and save it in UTF-8, then it works amazingly! Thank you guys for all your efforts!"

I'll be happy to screenshare with you if you wish to try it on the macbook

THanks

**Comment by alexanderby** [comment]
@acohen27 Encoding is not a problem in this case. I've pushed an update 3.4.1 yesterday, could you please check if the issue remains?

**Comment by acohen27** [comment]
Hi there, 

Unfortunately, the scroll issue still persists. I did try to adjust some css and the best I was able to achieve was it "stutter" every 50 ms . (down, stop. down. stop. down. stop. down. stop. etc)

On an interesting note, when I go into 
- google spreadsheet (works)
- google docs (doesn't work)
- google drive (the scroll works only if I have the mouse on the bottom half of the folders listview.)

I also did notice that by changing the user agent to iPad, the scrolling bar becomes weird too.  Maybe that gives you some clues

Sorry I am not much of help. :( 

Thanks again for the awesome chrome extension

**Comment by Dariuzs** [comment]
Same problem here!
Windows 8. Chrome v. 51.
Scrolling works in every page but not in Gmail.

**Comment by alexanderby** [comment]
@Dariuzs What device do you use? Is it a trackpad or a mousewheel?

**Comment by Dariuzs** [comment]
Mousewheel.
Microsoft Wireless Mobile 3000 v2.
https://www.microsoft.com/accessories/en-us/products/mice/wireless-mobile-mouse-3000/2ef-00013

**Comment by sparrc** [comment]
I  have this issue as well

**Comment by alexanderby** [comment]
Luckily I caught this bug with my wireless mouse, so now everybody please reload your GMail pages. Should be OK now.

**Comment by acohen27** [comment]
Well done! It's been a week and it is working like a charm. Ah ha!

May I ask if there is any difference between wireless mouse, usb mouse, and trackpad? 

Thanks!

**Comment by Dariuzs** [comment]
Yes, well done!
Thanks very much!!!
Dario
ᐧ
