### ISSUE TITLE
What about button (like "developer mode") to disable auto-syncing every 15 minutes?

### ISSUE THREAD

**Issue by risualiser** [alexanderby/darkreader#312]
Or, maybe, not sync in current session if user changed something in code (and make a warning that code will be updated if user reopens browser).

**Comment by alexanderby** [comment]
It is planned that user will have it's own separate config. So, the main config will continue to synchronize, and the users's one will override the values.

**Comment by risualiser** [comment]
Ok, this solution is from #143, I'll close the issue.
