### ISSUE TITLE
Youtube fullscreen wrongly inverted - Firefox Quantum

### ISSUE THREAD

**Issue by 3minutePython** [alexanderby/darkreader#313]
I'm using Darkreader on Mozilla Firefox for Ubuntu, canonical-1.0, Version 59.0.1(64-bit).

All is well except when playing youtube fullscreen, then it inverts the whole video color. Tried tinkering with the fix_inversion.json file to no avail.

Please help.

**Comment by risualiser** [comment]
There is a special dark theme on YouTube.
Try to turn it on (press on your avatar in upper right corner > dark theme).
If that didn't help, stay with this dark theme, open Dark Reader settings and press "Toggle www.youtube.com" (or write this address in site list manually).

**Comment by 3minutePython** [comment]
Thanks risualiser.

I didn't know that exist. I shall close this as solved then. Cheers.

**Comment by risualiser** [comment]
It wasn't necessary to close the issue. 
Maybe, that will be fixed later.
Anyway, thanks for the report.

**Comment by alexanderby** [comment]
Try it with the latest update.
