### ISSUE TITLE
Black page while scrolling in Firefox

### ISSUE THREAD

**Issue by sidharthv96** [alexanderby/darkreader#320]
Firefox : 59.0.1
OS : macOS High Sierra
I have max mouse speed and scroll speed enabled in my OS.
So, when scrolling fast in long pages, it takes about 2 seconds for the content to be visible. 
Till then, the screen is completely blank. There is no issue when extension is disabled or while using the Dark Mode addon.
But when I apply the rules from dark reader inside DarkMode as a custom rule, the issue pops up.
Is this a Mozilla bug? Chrome used to work fine for me.

**Comment by alexanderby** [comment]
The more content the page has, the slower will be the rendering. Also Firefox filter rendering is more buggy then Chrome. But recently Chrome introduced more filter bugs.

So, in a day or two you will be able to try another filter-less approach. It will be gradually improved and I hope it will become the default soon.

**Comment by alexanderby** [comment]
Since v4.0.0 you can try Static Themes, they should be more performant, though some backgrounds may be wrongly displayed.

**Comment by alexanderby** [comment]
Dynamic Theme mode doesn't use CSS filters and should not cause such issues.
