### ISSUE TITLE
Default 'toggle' hotkey does not work

### ISSUE THREAD

**Issue by sublayer** [alexanderby/darkreader#322]
**Browser:** Chrome Version 65.0.3325.181 (Official Build) (64-bit)
**OS:** Win10

- Default Alt+Shift+D does not toggle
- Tried on multiple machines
- If I set the same hotkey combination to other shortcuts, like "Toggle current site", it works fine. Only generic "Toggle" doesn't work

**Comment by alexanderby** [comment]
Fixed in v4.0.1
