### ISSUE TITLE
Toggle hotkey not working (FF)

### ISSUE THREAD

**Issue by Symbai** [alexanderby/darkreader#330]
Installed the FF extension and the default toggle hotkey ALT+SHIFT+D not working. If I press the hotkey then it opens the Menu -> File menu of FF instead (German version of FF).

FF 59.0.2
Dark Reader 4.0

**Comment by Kharmium** [comment]
Got the same problem. Just switched from Chrome to Firefox 59.0.2 and this is the only thing not working.

The current site toggle works ok (Alt+Shift+A). Dark REader 4.0.0

**Comment by alexanderby** [comment]
Seems I forgot to publish 4.0.1 to Firefox. Another problem is that Firefox has no way to edit the hotkeys.
