### ISSUE TITLE
Feedback requested: Page-Requested Reader Mode

### ISSUE THREAD

**Issue by jab** [alexanderby/darkreader#332]
I just wrote up a proposal for a standard I think you'd find interesting: https://github.com/jab/reader-mode

If you have a moment, please take a peek and let me know what you think.

Thanks for any feedback, and thanks for the great work on this extension!

**Comment by alexanderby** [comment]
This extension is aims to care the eyes, but not reducing the information noise. In my opinion bad UX  is a problem of website a owner and it should not be changed by using extra APIs, but changing website creators minds.
