### ISSUE TITLE
Feature Request: Site Specific Dark Skin

### ISSUE THREAD

**Issue by taufiqahmed** [alexanderby/darkreader#34]
For example specific Skin for most commonly used websites by Extension User. 
1.Facebook
2.Google
3.Wikipedia
4.Travel Sites such as Tripadvisor
5. News Sites (Mashable, Verge, TC etc)
6. Youtube
7. Dev Sites (stackexchange, product hunt)

and many more. I guess there wont be more than 100 sites which we can skin.

**Comment by deathtrip** [comment]
For site specific skins there's already the stylish extension.
No need to bloat this extension.

**Comment by oxysoft** [comment]
Dark Reader already works really well with most of the websites you've listed, so I'm not sure exactly what you mean. I would appreciate though if there was a way to disable inverting of certain pictures on certain websites using pattern matching.

**Comment by alexanderby** [comment]
Dynamic Theme should generate themes pretty well, though it require some resources at first load, especially for YouTube. Maybe I could ship generated themes for popular websites, but they will loose the ability to modify brightness and contrast.
