### ISSUE TITLE
contrast/brightness settings should not apply to images

### ISSUE THREAD

**Issue by sparrc** [alexanderby/darkreader#35]
Hello,

First off thanks for the great chrome extension :)

Some people might disagree with me, but I would prefer if images were not affected by the Dark Reader contrast/brightness settings. The reason is that I want to turn down the brightness of text and backgrounds, but still have the original images on the pages I am reading.

If not a default setting, maybe there could be an option for it?

**Comment by alexanderby** [comment]
20% shade was removed from reverted blocks. Not touching these blocks at all will be possible when #34 will be done.
