### ISSUE TITLE
Error: Cannot find module './Tab'

### ISSUE THREAD

**Issue by duza** [alexanderby/darkreader#352]
@alexanderby Hi. I tried to execute ```npm run debug```, but got an error: ```Error: Cannot find module './Tab'```. I think you should change [this](https://github.com/alexanderby/darkreader/blob/master/src/ui/controls/tab-panel/index.tsx#L3) line as follows: ```import Tab from './tab';```

**Comment by alexanderby** [comment]
Looks like I have case-insensitive file system. Consider submitting PR.
