### ISSUE TITLE
[bug] Some sites have blurred fonts when in dark mode

### ISSUE THREAD

**Issue by KroniK907** [alexanderby/darkreader#45]
I have had a somewhat odd issue. On some sites (specifically the stackexchange.com site) I have noticed that the text is often blurred or fuzzy when dark reader is on, but is clear and sharp when turned off. 

It is very strange because it only affects some pages of stackexchange and not others. For example, this page:

http://serverfault.com/questions/162018/force-ssh-to-use-a-specific-shell

Shows up blurry for me when dark reader is on. Here are some screenshots of the difference on my monitor:

[Fuzzy Dark Reader page](http://i.imgur.com/DFy2EwK.png)

[Crisp Standard page](http://i.imgur.com/J1BMXlw.png) (Darkreader was turned off for this screenshot)

However, other pages from the same website don't have this issue. For example: http://serverfault.com/questions/811736/i-accidentally-deleted-var-log-syslog-now-rsyslog-wont-log-anything 

I am currently running:

OS: Windows 10
Browser: Google Chrome 55.0.2883.21 beta (64-bit)
Darkreader: 3.4.3

**Comment by KroniK907** [comment]
I have found that forcing a font will fix this issue, however I'm not sure I want to force a single font across my entire browser, so this seems like a poor fix for this issue.

**Comment by alexanderby** [comment]
Hi. I've found out that in Chrome 55 this is caused by sepia filter. I will post a Chromium bug if there is no yet.

**Comment by alexanderby** [comment]
Reported a bug https://bugs.chromium.org/p/chromium/issues/detail?id=660310

**Comment by alexanderby** [comment]
Fixed.

**Comment by wavebit** [comment]
The font outline is still blurred on most sites compared to the original.
If I change the render mode from dynamic to static, the font outlline is clear and sharp as original, but some elements on the webpage are not visible.
----------------------
Windows 10
Chrome 70.0.3538.102
Dark Reader 4.6.12

**Comment by alexanderby** [comment]
@wavebit What is the DPI of your display? This can be caused by sub pixel rendering. If you make a screen shot and zoom in, you should notice that.
