### ISSUE TITLE
Lower permission requirement to activeTab

### ISSUE THREAD

**Issue by ghatchue** [alexanderby/darkreader#61]
Is it possible to lower the permission requirement in the manifest to activeTab instead of<all_urls>?
That seems aggressive for what the extension does.

**Comment by DanRathbun** [comment]
Or perhaps make it a option changeable by the user ?

**Comment by ghatchue** [comment]
It probably shouldn't be changeable by the user, because <any_urls> would require more privileges than are allowed for some users.

**Comment by DanRathbun** [comment]
I don't know,...  I can toggle certain sites on and off now.

**Comment by ghatchue** [comment]
This isn't about toggling sites on and off. The feature request is to lower the permission requirement to limit what the extension has access to.

**Comment by alexanderby** [comment]
This extension will not work without `<all_urls>` permission. You will get an error `Cannot access contents of url "...". Extension manifest must request permission to access this host.`.

**Comment by alexanderby** [comment]
I've added a privacy policy http://darkreader.org/privacy.html
