### ISSUE TITLE
Amazon.com search textbox is black on black

### ISSUE THREAD

**Issue by razzintown** [alexanderby/darkreader#7]
Text in searchbox of Amazon.com is unreadable because it is black text on a black searchbox. Text becomes white sometimes after clicking the textbox, but never while editing the text.

**Comment by sparrc** [comment]
I don't see this problem, for me it's white on black

**Comment by alexanderby** [comment]
This could be caused by presence of background in "style" attribute, some hack for ancient browsers. Google search box still has it.

**Comment by razzintown** [comment]
The Google search box is white on black for me. Amazon is still black on black while the textbox is active. 
I don't understand what you mean about some hack for ancient browsers. I'm using Chrome Version 48.0.2564.97 (64-bit) on OS X 10.11.3, and I know it also happens on my Windows 7 and Linux computers.
![screen shot 2016-02-05 at 6 22 30 pm](https://cloud.githubusercontent.com/assets/1140256/12863595/85ba4244-cc35-11e5-8856-5cf4feca1d9b.png)

**Comment by alexanderby** [comment]
This is how it looks for me
![image](https://cloud.githubusercontent.com/assets/9638588/12865363/a85fe1ac-ccba-11e5-8093-c37e0675b91a.png)

Could you please post a direct link, if it is not http://www.amazon.com/ ?
Also you may find s search box element in Dev Tools and send me screenshot. I suppose there is a 1px background image, and Dark Reader inverts the content of the search box.

**Comment by razzintown** [comment]
In your screenshot, is the text box in focus (the cursor is editing the text)?

**Comment by alexanderby** [comment]
in both cases the text is visible, maybe there is some regional or device style sheet difference. Try to inspect the search box element in Dev Tools, I suppose there is 1px stretched background image, so Dark Reader thinks that it should not be inverted.
This is how it looks for Google Search, so I had to write a fix for this case:
![dr-searchbox-1px](https://cloud.githubusercontent.com/assets/9638588/13723375/eccd8ca2-e873-11e5-90b8-17aaca5f0f1d.png)

**Comment by razzintown** [comment]
Here is a screenshot:
![screenshot](https://cloud.githubusercontent.com/assets/1140256/14666665/bdb8148e-068f-11e6-91f1-a4feff8b1db1.jpg)


Here is the input box HTML (when the form is active):
`<input type="text" id="twotabsearchtextbox" value name="field-keywords" autocomplete="off" class="nav-input" tabindex="19" style="cursor: auto; background-image: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAALHRFWHRDcmVhdGlvbiBUaW1lAEZyaSAxMiBOb3YgMjAxMCAxOTowNzowMiArMTIwMOGr8p4AAAAHdElNRQfaCwwGBxwduq16AAAACXBIWXMAAAsSAAALEgHS3X78AAAABGdBTUEAALGPC/xhBQAAAfJJREFUeNqVkk1vElEUhp87X4CIFhhMG0toMC5K3Lgxbro10bhxY2Jc+CO666Y/oP/DxFVjTKM7l1apTdM0JSU0LSg0WqaUjwE6MDNebGpKBYlndc+55zw5H6/gim2UUd0qs5Uy6VaTa7EYdtOmUN7naHER92q+dtnZ2UFpHTOTXWfuwxrfYlNUHz1lxvdIVyx6MuXHPwFeBLW2z+29Pepr7ziUof7SEq1CibCEmKMAymXH6SD6LrpzRndQPIjNz9P3odu2URlhQ4C+ghcM0JpLEchkzrv7eIDS62JYP2lPBJS2cIMhyrMpwo+fMbW8jLhhc2t3F906pjoK8GcH29vonoenRDk1m5zcvUM6ZuJvZEnmcljT09hbR6iVIuLJw/PxhgAOPOj26Gk1nEQCNWAQ7XS4bxvw8hWuGedeo4iR+/y7+OtfgM1N9OIBwnFQ5SLdZJJ2JML17BdqEuYHgmiahsjnx4zw/i2fslm8dht/YQHx/AWpfI50/ZTKm9d8lykiHkf4/hjA6ipnF++VFRS7T1AoaDejyCEYlHmWNeEKF9YISz30CBkGirxKUIZGamAsQG2hux66BAipi1A6g/5fAM/HkGrUFfmr6wSSiWHJTwQoPrq8hCYEGDoh0xzfwUhyIY9ROkRrNKQ65e1P6uM7+AW+ibcHEM1ixAAAAABJRU5ErkJggg=="); background-position: 275px 0px; background-repeat: no-repeat;">`
