### ISSUE TITLE
background img inverted...Need Help!

### ISSUE THREAD

**Issue by ghost** [alexanderby/darkreader#71]
I have tried changing sites_fixes_v2.json
{
            "url": "blog.naver.com",
            "selectors": ".se_mediaImage, .__se_img_el"
        },

but it doesn't work for the sub directorties such as 

blog.naver.com/abcd
blog.naver.com/123

I'm wondering how I can fix this?

**Comment by PeterHindes** [comment]
try using a * (wildcard)
(I honestly have not dealt with this, just a suggestion off the top of my head)

**Comment by alexanderby** [comment]
Should work well with Dynamic Theme mode.
