### ISSUE TITLE
Disqus comments unreadable in dark mode

### ISSUE THREAD

**Issue by rituraj22** [alexanderby/darkreader#76]

**Comment by freMea** [comment]
Example [here](http://vuejsdevelopers.com/2017/07/08/vue-js-3-ways-code-splitting-webpack/)

**Comment by freMea** [comment]
@alexanderby 
Will you consider to fix this issue using the example page (scroll to bottom) given above ?
Will you consider the current waiting pull requests that fixes some sites and make a new release ?

**Comment by alexanderby** [comment]
This week I will make an ability to set common rules (like currently common selectors) so that it will be possible to set background for such widgets.

I will look into your PR, config changes do not require new release, extension requests changes every 15 minutes.

**Comment by alexanderby** [comment]
Should have been fixed.
