### ISSUE TITLE
Ignore images

### ISSUE THREAD

**Issue by armandino** [alexanderby/darkreader#8]
This is more of a feature request. It'd be great if the extension had an option to ignore images.

**Comment by alexanderby** [comment]
The extension tries to ignore images. If some images (usually backgrounds) are wrongly inverted, the [sites_fixes.json](https://github.com/alexanderby/darkreader/blob/master/src/config/sites_fixes.json) should be edited.

**Comment by armandino** [comment]
I see... Thanks Alex.
