### ISSUE TITLE
eBay Picture Inverting

### ISSUE THREAD

**Issue by c-borgia** [alexanderby/darkreader#80]
Hey there, I am not sure if this is the right place for this, but... 

DarkReader inverts the black borders (to white) when viewing eBay images.

Example (I hope this works) 
http://www.ebay.com/itm/IBANEZ-AR720-BSQ-Bursted-Smokey-Quartz-Guitar-w-Abalone-Binding-Gold-Hdwr-Case-/272733709439?hash=item3f8032247f:g:z7oAAOSw6YtZTp~L 
(EDIT: OH! That just takes you to the item itself, I mean, after you click the picture, to see the rest of the pictures in the window.)

With DarkReader on, in my computer, at least (Windows 8), the border which is supposed to be black is flipped to white... and (as you will see) the image less "impressive", with DarkReader on. More faded.

I can imagine this would be a nightmare, if it has to be done case by case, but if there is a way to sort all "eBay image viewing" out, with a simple code, maybe that's something that could be done.
Thank you.

**Comment by alexanderby** [comment]
Should be fixed with Dynamic Mode.
