### ISSUE TITLE
Feature Request: separate settings for image and video

### ISSUE THREAD

**Issue by kurtontheway** [alexanderby/darkreader#82]
I've become a heavy user of darkreader recently, I use it not only at night but also in the daytime. Images and videos are ok to dim at night, but I find it hard to read in the daytime. I will help If there are separate settings for image/video.

**Comment by alexanderby** [comment]
If you mean that colors are less saturated, this is a problem with Chrome built-in filters. I've started to work on fixes, hope it will be finally possible to replace old filtering engine with a new one.

**Comment by alexanderby** [comment]
Dynamic Theme does not use CSS Filters and leaves images colors untouched (inverting light background images and dark icons only, though not ideally yet).
