### ISSUE TITLE
Google spreadsheet is not dark anymore

### ISSUE THREAD

**Issue by Rastkun** [alexanderby/darkreader#89]
![screenshot - 19_9_2017 15_59_33](https://user-images.githubusercontent.com/32092717/30584320-8fea3b3e-9d53-11e7-9a13-9979b31b6d63.png)

Just happened today(19Sep2017). Yesterday it was dark and fine. Side effect of Fixed YouTube panel overlay maybe?

**Comment by alexanderby** [comment]
I decided to not invert <canvas> by default. I'll make a fix for Google Docs.

**Comment by Rastkun** [comment]
Thanks! That was fast.
