### ISSUE TITLE
Maybe move devtools to a separate page?

### ISSUE THREAD

**Issue by BANOnotIT** [alexanderby/darkreader#92]
It isn't very comfort to use devtools in "modal".

**Comment by alexanderby** [comment]
I agree. In next version a planned to make an editor with settings groups, theme editor, e.t.c for advanced users on separate page. Current solution is the simplest one, but as a workaround you can copy text from the text area, paste it into JSON editor and then past it back.

**Comment by J-e-r-e-m-i-a-h** [comment]
is there anyway to make it... commit forever? every 10ish minutes i have to reopen the panel and click "apply" again

**Comment by RalphLesch** [comment]
The extension updates (downloads) the current [fix_inversion.json](/alexanderby/darkreader/blob/master/src/config/fix_inversion.json) from github every 15 minutes, which "overwrites" the local custom config, although the changes made in the inversion fix editor are not changed.
It would be probably best to separate the local from the remote version and to overwrite the synced / downloaded remote version by the local one. Or in other words: merge local and remote versions by favoring local over remote.
When simply overwriting the remote site specific configs with the local ones, merge errors should be minimal.

**Comment by alexanderby** [comment]
This will appear the next release. Also text format will be simplified.
