### ISSUE TITLE
youtube subscription email preview images get inverted in gmail

### ISSUE THREAD

**Issue by Theyrealone** [alexanderby/darkreader#97]
"[class$=video-spotlight-width] { background: rgba(255,255,255,.4) !important; }"
this lines can set the background of such images to black it seems(not in source)
the images are now a part of table that has the image as part of its background.

        {
            "url": [
                "google.*",
                "google.*.*"
            ],
            "invert": [
                ".gbii, .gbip, .azp, .aLF-aPX-KP, .irc_bg, .RY3tic, canvas.circle"
            ],
            "noinvert": [
                ".irc_mi, .irc_rii, .irc_mut, .amI, .amJ, .adk, .adj, [src*='ic_'], [src*='black']",
                "input[style*='data:image']"
            ],
            "rules": [
                ".pI { background: rgba(255,255,255,.7) !important; }",
                ".eB { background: rgba(255,255,255,.4) !important; }",
                "[class$=video-spotlight-width] { background: rgba(255,255,255,.4) !important; }"
            ]
        },

I don't know how to write a selector that causes it not to invert the class' background.

**Comment by alexanderby** [comment]
Does it work now?

**Comment by Theyrealone** [comment]
no, i found possible fix
