### ISSUE TITLE
How to change Black to something else?

### ISSUE THREAD

**Issue by moccon** [alexanderby/darkreader#99]
What to put in the Developer code to change the Black to something warmer?
Or Greytone shades..  no not 50 shades...

**Comment by nemanjan00** [comment]
Also interested in this one... 

IT would be grate to have solarized dark theme... :D

**Comment by alexanderby** [comment]
I have started to work on using custom SVG filters but Chrome had bugs with dynamic content. I will try suggested workaround soon. Then it would be possible to experiment with it.

**Comment by moccon** [comment]
Or for now, just leave the code we have to past in developertools here?   
(mid-grey)

**Comment by alexanderby** [comment]
Dynamic Theme makes neutral text a little bit yellow. To make background more grey, decrease the contrast.
